package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/tasuku43/cc-bash-guard/internal/domain/semantic"
)

const (
	docPath     = "docs/user/SEMANTIC_COVERAGE.md"
	startMarker = "<!-- BEGIN GENERATED SEMANTIC FIELD REFERENCE -->"
	endMarker   = "<!-- END GENERATED SEMANTIC FIELD REFERENCE -->"
)

func main() {
	root, err := repoRoot()
	if err != nil {
		fatal(err)
	}
	path := filepath.Join(root, docPath)
	content, err := os.ReadFile(path)
	if err != nil {
		fatal(err)
	}

	generated := renderFieldReference()
	updated, err := replaceGeneratedBlock(string(content), generated)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		fatal(err)
	}
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd, nil
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return "", fmt.Errorf("could not find repository root from current directory")
		}
		wd = parent
	}
}

func renderFieldReference() string {
	var b bytes.Buffer
	b.WriteString(startMarker)
	b.WriteString("\n")
	b.WriteString("<!-- Generated by: go generate ./internal/domain/semantic -->\n")
	b.WriteString("<!-- Source: internal/domain/semantic/schema_*.go -->\n\n")
	b.WriteString("## Field Reference\n\n")
	b.WriteString("The field names below are generated from the semantic schema registry.\n")
	b.WriteString("Field meanings come from the current schema source.\n")

	for _, schema := range semantic.AllSchemas() {
		detail := coverageDetails[schema.Command]
		fmt.Fprintf(&b, "\n### %s\n\n", schema.Command)
		if schema.Description != "" {
			fmt.Fprintf(&b, "%s\n\n", schema.Description)
		}
		writeDetailList(&b, "Common safe/read-only examples", detail.ReadOnlyExamples)
		writeDetailList(&b, "Common mutating/destructive examples", detail.MutatingExamples)
		if detail.RecommendedPolicy != "" {
			fmt.Fprintf(&b, "**Suggested policy style:** %s\n\n", detail.RecommendedPolicy)
		}
		writeDetailList(&b, "Known limitations / conservative fallback cases", detail.Limitations)
		if detail.ExplainCommand != "" {
			b.WriteString("Inspect parser output:\n\n")
			fmt.Fprintf(&b, "```sh\ncc-bash-guard explain %q\n```\n\n", detail.ExplainCommand)
		}
		if detail.YAML != "" {
			b.WriteString("Example rule snippet:\n\n")
			fmt.Fprintf(&b, "```yaml\n%s\n```\n\n", strings.TrimSpace(detail.YAML))
		}
		b.WriteString("| Field | Type | Meaning |\n")
		b.WriteString("| --- | --- | --- |\n")
		for _, field := range schema.Fields {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", field.Name, field.Type, escapeTableCell(field.Description))
		}
		if len(schema.Notes) > 0 {
			b.WriteString("\nNotes:\n\n")
			for _, note := range schema.Notes {
				fmt.Fprintf(&b, "- %s\n", note)
			}
		}
	}

	b.WriteString("\n")
	b.WriteString(endMarker)
	b.WriteString("\n")
	return b.String()
}

func writeDetailList(b *bytes.Buffer, title string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(b, "**%s:**\n\n", title)
	for _, value := range values {
		fmt.Fprintf(b, "- `%s`\n", value)
	}
	b.WriteString("\n")
}

func replaceGeneratedBlock(content, generated string) (string, error) {
	start := strings.Index(content, startMarker)
	if start == -1 {
		return "", fmt.Errorf("missing start marker %q in %s", startMarker, docPath)
	}
	end := strings.Index(content, endMarker)
	if end == -1 {
		return "", fmt.Errorf("missing end marker %q in %s", endMarker, docPath)
	}
	end += len(endMarker)
	return content[:start] + strings.TrimRight(generated, "\n") + content[end:] + "\n", nil
}

func escapeTableCell(value string) string {
	return strings.ReplaceAll(value, "|", `\|`)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

type commandCoverageDetail struct {
	ReadOnlyExamples  []string
	MutatingExamples  []string
	RecommendedPolicy string
	Limitations       []string
	ExplainCommand    string
	YAML              string
}

var coverageDetails = map[string]commandCoverageDetail{
	"git": {
		ReadOnlyExamples:  []string{"git status", "git diff", "git log"},
		MutatingExamples:  []string{"git push --force", "git reset --hard", "git clean -fdx"},
		RecommendedPolicy: "Allow narrow read-only verbs; deny force-like push/reset/clean; keep broad git behavior in ask.",
		Limitations:       []string{"git aliases", "hooks", "remote server policy", "repository contents"},
		ExplainCommand:    "git push --force origin main",
		YAML: `permission:
  allow:
    - name: git read-only
      command:
        name: git
        semantic:
          verb_in: [status, diff, log, show]
  deny:
    - name: git force push
      command:
        name: git
        semantic:
          verb: push
          force: true`,
	},
	"aws": {
		ReadOnlyExamples:  []string{"aws sts get-caller-identity"},
		MutatingExamples:  []string{"aws iam delete-user", "aws cloudformation deploy", "aws s3 rm"},
		RecommendedPolicy: "Allow exact low-risk service/operation/profile combinations; ask or deny write-capable services and operations.",
		Limitations:       []string{"AWS IAM authorization", "resource ARNs", "request bodies", "service-specific side effects"},
		ExplainCommand:    "aws sts get-caller-identity --profile dev",
		YAML: `permission:
  allow:
    - name: AWS identity
      command:
        name: aws
        semantic:
          service: sts
          operation: get-caller-identity
  ask:
    - name: AWS IAM changes
      command:
        name: aws
        semantic:
          service: iam`,
	},
	"kubectl": {
		ReadOnlyExamples:  []string{"kubectl get pods", "kubectl describe pod app"},
		MutatingExamples:  []string{"kubectl apply -f file.yaml", "kubectl delete pod app", "kubectl rollout restart deployment/app"},
		RecommendedPolicy: "Allow read-only verbs in known contexts/namespaces; ask for apply/exec/rollout; deny deletes where needed.",
		Limitations:       []string{"manifest contents", "cluster admission", "RBAC", "kubeconfig contents", "object state"},
		ExplainCommand:    "kubectl get pods -n prod",
		YAML: `permission:
  allow:
    - name: kubectl read-only prod
      command:
        name: kubectl
        semantic:
          verb_in: [get, describe]
          namespace: prod
  deny:
    - name: kubectl prod delete
      command:
        name: kubectl
        semantic:
          verb: delete
          namespace: prod`,
	},
	"gh": {
		ReadOnlyExamples:  []string{"gh pr view", "gh issue view", "gh repo view"},
		MutatingExamples:  []string{"gh pr merge", "gh issue close", "gh release delete", "gh secret set"},
		RecommendedPolicy: "Allow narrow read-only areas; deny mutating gh api methods; keep broad gh behavior in ask.",
		Limitations:       []string{"gh api request body contents", "GraphQL mutation details", "server authorization", "extension behavior"},
		ExplainCommand:    "gh api repos/OWNER/REPO --method GET",
		YAML: `permission:
  allow:
    - name: gh read-only
      command:
        name: gh
        semantic:
          area_in: [pr, issue, repo]
          verb_in: [view, list]
  deny:
    - name: gh mutating api
      command:
        name: gh
        semantic:
          area: api
          method_in: [POST, PATCH, PUT, DELETE]`,
	},
	"gws": {
		ReadOnlyExamples:  []string{"gws drive files list"},
		MutatingExamples:  []string{"gws gmail messages +send", "gws drive files delete"},
		RecommendedPolicy: "Allow explicit service/resource_path/method rules; use inferred booleans only as conservative aids.",
		Limitations:       []string{"dynamic Google Discovery surfaces", "method-name mutation inference", "request bodies", "server authorization"},
		ExplainCommand:    "gws drive files list",
		YAML: `permission:
  allow:
    - name: gws drive file list
      command:
        name: gws
        semantic:
          service: drive
          resource_path: [files]
          method: list
  ask:
    - name: gws mutating methods
      command:
        name: gws
        semantic:
          mutating: true`,
	},
	"helm": {
		ReadOnlyExamples:  []string{"helm list", "helm status", "helm get values"},
		MutatingExamples:  []string{"helm upgrade --install", "helm uninstall", "helm rollback"},
		RecommendedPolicy: "Allow inspection verbs; ask for install/upgrade/rollback/uninstall/plugin changes.",
		Limitations:       []string{"chart contents", "values files", "templates", "plugins", "kube credentials", "cluster effects"},
		ExplainCommand:    "helm status my-release -n prod",
		YAML: `permission:
  allow:
    - name: helm inspection
      command:
        name: helm
        semantic:
          verb_in: [list, status, history, get, show, search, template, lint]
  ask:
    - name: helm changes
      command:
        name: helm
        semantic:
          verb_in: [install, upgrade, rollback, uninstall]`,
	},
	"helmfile": {
		ReadOnlyExamples:  []string{"helmfile diff"},
		MutatingExamples:  []string{"helmfile apply", "helmfile sync", "helmfile destroy"},
		RecommendedPolicy: "Allow review commands only with expected environment/file/context; ask for apply/sync/destroy.",
		Limitations:       []string{"helmfile state", "nested helm behavior", "values files", "release state", "cluster effects"},
		ExplainCommand:    "helmfile -e prod diff",
		YAML: `permission:
  allow:
    - name: helmfile prod diff
      command:
        name: helmfile
        semantic:
          verb: diff
          environment: prod
  ask:
    - name: helmfile prod changes
      command:
        name: helmfile
        semantic:
          verb_in: [apply, sync, destroy]
          environment: prod`,
	},
	"argocd": {
		ReadOnlyExamples:  []string{"argocd app get my-app", "argocd app list"},
		MutatingExamples:  []string{"argocd app sync my-app", "argocd app delete my-app"},
		RecommendedPolicy: "Allow read-only app verbs for known apps/projects; ask for sync/rollback/delete.",
		Limitations:       []string{"Argo CD RBAC", "app manifests", "sync waves", "hooks", "server-side effects"},
		ExplainCommand:    "argocd app get my-app",
		YAML: `permission:
  allow:
    - name: argocd app read
      command:
        name: argocd
        semantic:
          verb_in: ["app get", "app list", "app diff"]
  ask:
    - name: argocd app sync
      command:
        name: argocd
        semantic:
          verb: app sync`,
	},
	"terraform": {
		ReadOnlyExamples:  []string{"terraform plan", "terraform show", "terraform validate"},
		MutatingExamples:  []string{"terraform apply", "terraform destroy", "terraform state rm", "terraform workspace delete"},
		RecommendedPolicy: "Allow review/read-only subcommands narrowly; ask for apply/import/state/workspace writes; deny auto-approved destroy.",
		Limitations:       []string{"providers", "modules", "plan contents", "state contents", "backend credentials", "provisioner effects"},
		ExplainCommand:    "terraform plan -out=tfplan",
		YAML: `permission:
  allow:
    - name: terraform review
      command:
        name: terraform
        semantic:
          subcommand_in: [validate, plan, show, output]
  deny:
    - name: terraform auto destroy
      command:
        name: terraform
        semantic:
          subcommand: destroy
          auto_approve: true`,
	},
	"docker": {
		ReadOnlyExamples:  []string{"docker ps", "docker images", "docker inspect"},
		MutatingExamples:  []string{"docker run --privileged", "docker system prune -a --volumes", "docker compose up"},
		RecommendedPolicy: "Allow inspection verbs; deny privileged/socket/root mounts and destructive prune; ask for run/compose/build.",
		Limitations:       []string{"images", "Dockerfiles", "Compose files", "daemon state", "container entrypoints", "mounted file contents"},
		ExplainCommand:    "docker run --privileged alpine",
		YAML: `permission:
  allow:
    - name: docker inspection
      command:
        name: docker
        semantic:
          verb_in: [ps, images, inspect, logs, version, info]
  deny:
    - name: docker socket mount
      command:
        name: docker
        semantic:
          docker_socket_mount: true`,
	},
	"xargs": {
		ReadOnlyExamples:  []string{"find . -type f -print0 | xargs -0 -r grep -n TODO", "printf '%s\\n' README.md | xargs cat"},
		MutatingExamples:  []string{"xargs rm -rf", "xargs gh pr merge", "xargs git reset"},
		RecommendedPolicy: "Allow only explicit xargs semantic rules for known inner commands; keep dynamic stdin-derived argv in mind.",
		Limitations:       []string{"stdin contents", "runtime argv expansion", "paths supplied by earlier pipeline commands", "parallel process effects"},
		ExplainCommand:    "xargs -0 -r grep -n TODO",
		YAML: `permission:
  allow:
    - name: xargs grep readonly
      command:
        name: xargs
        semantic:
          inner_command: grep
          null_separated: true
          no_run_if_empty: true
          replace_mode: false
          parallel: false
  deny:
    - name: xargs rm
      command:
        name: xargs
        semantic:
          inner_command: rm`,
	},
}
