version: 2

project_name: cmdproxy

before:
  hooks:
    - go test ./...

builds:
  - id: cmdproxy
    main: ./cmd/cmdproxy
    binary: cmdproxy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: archives
    ids:
      - cmdproxy
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_
      {{- if eq .Os "darwin" -}}macos{{- else -}}{{ .Os }}{{- end -}}_
      {{- if eq .Arch "amd64" -}}x64{{- else -}}{{ .Arch }}{{- end -}}

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  prerelease: auto
